    <div class="large-12 columns">
        <span id="signinButton">
            <span
              class="g-signin"
              data-callback="signinCallback"
              data-clientid="1064499145733-efcse420dc7pp7ul1mo77998bmfkmdo8.apps.googleusercontent.com"
              data-cookiepolicy="single_host_origin"
              data-requestvisibleactions="http://schema.org/AddAction"
              data-state="state12345678"
              data-scope="https://www.googleapis.com/auth/plus.login"
              data-width="wide"
              data-redirecturi="http://localhost/auth/google"
            >
            </span>
        </span>
    </div>
    <script type="text/javascript">
        (function() {
            var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
            po.src = 'https://apis.google.com/js/client:plusone.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
        })();
    </script>