            <?php
                $this->headTitle()->prepend($this->collection->getName());
            ?>
                <div class="large-8 columns">
                    <section id="articles">
                        <header>
                            <h2>Collection - <?php echo $this->collection->getName(); ?> </h2>
                            <ul class="button-group">
                            <?php if($this->collection->getId() != $this->activeCollection()->getId()): ?>
                                <?php
                                $setActiveUrl = $this->url(
                                    'collection/set-active',
                                    array(
                                        'id' => $this->collection->getId()
                                    )
                                );
                                $setActiveUrl .= '?redirect=' . urlencode($_SERVER['REQUEST_URI']);
                                ?>
                                <?php if($this->activeCollection()->isEdited()): ?>
                            <li>
                                <a class="tiny button" title="Set <?php echo $this->collection->getName(); ?> as active collection"
                                   href="<?php echo $setActiveUrl; ?>" data-reveal-id="modal-active">
                                    <span class="fa fa-paperclip"></span> Set as active
                                </a>
                            <div id="modal-active" class="reveal-modal small" data-reveal>
                                <h2>Set active collection</h2>
                                <p class="lead">Your existing active collection is edited . If you wish to continue, all unsaved changes will be lost</p>
                                <a class="tiny button" href="<?php echo $setActiveUrl; ?>">
                                    <span class="fa fa-folder-open"></span> Set <?php echo $this->collection->getName(); ?> as active collection
                                </a>
                                <a class="close-reveal-modal">&#215;</a>
                            </div>
                            </li>
                                <?php else: ?>
                            <li><a class="tiny button" title="Set <?php echo $this->collection->getName(); ?> as active collection"
                                   href="<?php echo $setActiveUrl; ?>">
                                <span class="fa fa-paperclip"></span> Set as active
                            </a></li>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php $articles = $this->collection->getArticles(); ?>
                            <?php if(count($articles)): ?>
                            <li>
                                <?php $exportUrl = $this->url('collection/export', array('id' => $this->collection->getId())); ?>
                                <a class="tiny button" href="<?php echo $exportUrl; ?>"
                                   title="Export citations in Vancouver format">
                                    <span class="fa fa-list-ol"></span> Export
                                </a>
                            </li>
                            <?php endif; ?>
                            </ul>
                        </header>
                        <?php
                        if(count($articles) > 1) {
                            $this->partialLoop()->setObjectKey('article');
                            echo $this->partialLoop('partials/article-truncated', $articles);
                        }
                        elseif(count($articles) == 1) {
                            reset($articles);
                            $article = current($articles);
                            echo $this->partial('partials/article', array('article' => $article));
                        }
                        else {
                        ?>
                        <p>The collection is empty.</p>
                        <?php } ?>
                    </section>
                </div>
                <div class="large-4 columns">
                    <?php echo $this->activeCollection()->render(); ?>
                </div>