            <?php
                $this->headTitle()->prepend($this->collection->getName());
            ?>
                <div class="large-8 columns">
                    <section id="articles" data-collection-name = "<?php echo $this->collection->getName(); ?>">
                        <header>
                            <h2>Collection - <?php echo $this->collection->getName(); ?> </h2>
                            <ul class="button-group">
                            <?php if($this->collection->getId() != $this->activeCollection()->getId()): ?>
                                <?php
                                $setActiveUrl = $this->url(
                                    'collection/set-active',
                                    array(
                                        'id' => $this->collection->getId()
                                    )
                                );
                                $setActiveUrl .= '?redirect=' . urlencode($_SERVER['REQUEST_URI']);
                                ?>
                            <li><a class="tiny button"
                                   title="Set <?php echo $this->collection->getName(); ?> as active collection"
                                   href="<?php echo $setActiveUrl; ?>">
                                <span class="fa fa-paperclip"></span> Set as active
                            </a></li>
                            <?php endif; ?>
                            <?php $articles = $this->collection->getArticles(); ?>
                            <?php if(count($articles)): ?>
                            <li>
                                <?php $exportUrl = $this->url('collection/export', array('id' => $this->collection->getId())); ?>
                                <a class="tiny button" href="<?php echo $exportUrl; ?>"
                                   title="Export citations in Vancouver format">
                                    <span class="fa fa-list-ol"></span> Export
                                </a>
                            </li>
                            <?php endif; ?>
                                <li>
                                    <?php $deleteUrl = $this->url('collection/delete', array('id' => $this->collection->getId())); ?>
                                    <a class="tiny button" href="<?php echo $deleteUrl; ?>"
                                       title="Delete collection">
                                        <span class="fa fa-trash-o"></span> Delete
                                       </a>
                                </li>
                            </ul>
                        </header>
                        <?php
                        if(count($articles) > 1) {
                            $this->partialLoop()->setObjectKey('article');
                            echo $this->partialLoop('partials/article-truncated', $articles);
                        }
                        elseif(count($articles) == 1) {
                            reset($articles);
                            $article = current($articles);
                            echo $this->partial('partials/article', array('article' => $article));
                        }
                        else {
                        ?>
                        <p>The collection is empty.</p>
                        <?php } ?>
                    </section>
                </div>
                <div class="large-4 columns">
                    <?php echo $this->activeCollection()->render(); ?>
                </div>