                <div class="large-8 columns">
                    <section id="articles">
                        <header>
                            <h2>Collection - <?php echo $this->collection->getName(); ?> </h2>
                            <?php if($this->collection->getId() != $this->activeCollection()->getId()): ?>
                            <a class="tiny button" href="<?php echo $this->url('collection/set-active', array('id' => $this->collection->getId())) . '?redirect=' . $_SERVER['REQUEST_URI']; ?>"><i class="fa fa-paperclip"></i>&nbsp; Set as active collection</a>
                            <?php endif; ?>
                            <?php $articles = $this->collection->getArticles(); ?>
                        </header>
                        <?php
                        if(count($articles) > 1) {
                            $this->partialLoop()->setObjectKey('article');
                            echo $this->partialLoop('partials/article-truncated', $articles);
                        }
                        elseif(count($articles) == 1) {
                            echo "<p>Only one article. Partial yet to be created.</p>";
                        }
                        else {
                        ?>
                        <p>The collection is empty.</p>
                        <?php } ?>
                    </section>
                </div>
                <div class="large-4 columns">
                    <?php echo $this->activeCollection()->render(); ?>
                </div>