<?php
    /** @var \Collection\Service\CollectionService $service */
    $service = $this->service;
    $collection = $service->getActiveCollection();
?>
            <aside id="active-collection" class="clearfix" data-edited="<?php echo $service->isEdited(); ?>">
                <h3>Active Collection <?php if($service->isEdited()){ ?><span>*</span><?php } ?></h3>
                <?php if($this->authService()->hasIdentity()): ?>
                <form method="post" action="<?php echo $this->url('collection/save') . '?redirect=' . urlencode($_SERVER['REQUEST_URI']); ?>">
                    <div class="row">
                        <div class="large-3 small-3 columns">
                            <label for="txt-collection-name" class="inline right">Name</label>
                        </div>
                        <div class="large-9 small-9 columns">
                            <input type="text" name="txt-collection-name"
                                   id="txt-collection-name" value="<?php echo $collection->getName(); ?>" style="margin-bottom: 0"/>

                        </div>
                    </div>
                <?php endif; ?>
                <?php if(!$this->authService()->hasIdentity() && $service->isEdited()): ?>
                    <div class="row">
                        <div class="alert-box info" data-alert>
                            Please login, if you wish to save this collection permanently
                            <a class="close" href="#">&times;</a>
                        </div>
                    </div>
                <?php endif; ?>
                <?php if(!count($collection)): ?>
                    <div data-alert class="alert-box info">
                        Your active collection is empty.
                        <a href="#" class="close">&times;</a>
                    </div>
                <?php endif; ?>
                    <div class="row"  style="margin-bottom:2em;">
                        <div class="large-12 columns">
                            <ol id="collection">
                                <?php
                                $this->partialLoop()->setObjectKey('article');
                                echo $this->partialLoop('partials/article-list', $collection->getArticles());
                                ?>
                            </ol>
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-12 columns">
                            <ul class="button-group right">
                            <?php
                                if($this->activeCollection()->getId() > 0 &&
                                    !$this->activeCollection()->isOpen($this->activeCollection()->getId())):
                            ?>
                                <?php $openUrl = $this->url('collection/open', array('id' => $this->activeCollection()->getId())); ?>
                                <?php if($this->activeCollection()->isEdited()): ?>
                                <li>
                                    <a class="tiny button" href="<?php echo $openUrl; ?>"
                                       data-reveal-id="modal-open-unedited">
                                        <span class="fa fa-folder-open"></span> Open
                                    </a>
                                    <div id="modal-open-unedited" class="reveal-modal small" data-reveal>
                                        <h2>Open collection</h2>
                                        <p>The collection is not yet saved. The changes won't be reflected on opening the collection. Alternatively, you might save and continue.</p>
                                        <a href="<?php echo $openUrl; ?>"
                                           class="tiny button"><span class="fa fa-folder-open"></span> Open anyway</a>
                                        <a class="close-reveal-modal">&#215;</a>
                                    </div>
                                </li>
                                <?php else: ?>
                                <li>
                                    <a class="tiny button" href="<?php echo $openUrl; ?>">
                                        <span class="fa fa-folder-open"></span> Open
                                    </a>
                                </li>
                                <?php endif; ?>
                            <?php endif; ?>
                                <?php if($this->authService()->hasIdentity()): ?>
                                <li><button type="submit" class="button tiny"><span class="fa fa-save"></span> Save</button></li>
                                    <?php if($collection->getId()): ?>
                                <li>
                                    <?php
                                        $deleteUrl = $this->url('collection/delete');
                                        if($collection->getId() != $this->activeCollection()->getOpenCollectionId()) {
                                            $deleteUrl .= '?redirect=' . urlencode($_SERVER['REQUEST_URI']);
                                        }
                                    ?>
                                    <a class="button tiny"
                                       data-reveal-id="modal-delete"
                                       href="<?php echo $deleteUrl; ?>">
                                        <span class="fa fa-trash-o"></span> Delete
                                    </a>
                                    <div id="modal-delete" class="reveal-modal small" data-reveal>
                                        <h2>Delete collection</h2>
                                        <p>Are you sure? Do you want to delete the collection <?php echo $collection->getName(); ?> permanently?</p>
                                        <a href="<?php echo $deleteUrl; ?>"
                                           class="tiny button"><span class="fa fa-trash-o"></span> Delete <?php echo $collection->getName(); ?></a>
                                        <a class="close-reveal-modal">&#215;</a>
                                    </div>
                                </li>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </ul>
                        </div>
                    </div>
                <?php if($this->authService()->hasIdentity()): ?>
                </form>
                <?php endif; ?>
            </aside>