<?php
    /** @var \Collection\Service\CollectionService $service */
    $service = $this->service;
    $collection = $service->getActiveCollection();
?>
            <aside id="active-collection" class="clearfix">
                <h3>Active Collection <?php if($service->isEdited()){ ?><span>*</span><?php } ?></h3>
                <?php if($this->authService()->hasIdentity()): ?>
                <form method="post" action="<?php echo $this->url('collection/save') . '?redirect=' . urlencode($_SERVER['REQUEST_URI']); ?>">
                    <div class="row">
                        <div class="large-3 small-3 columns">
                            <label for="txt-collection-name" class="inline right">Name</label>
                        </div>
                        <div class="large-9 small-9 columns">
                            <input type="text" name="txt-collection-name"
                                   id="txt-collection-name" value="<?php echo $collection->getName(); ?>" style="margin-bottom: 0"/>

                        </div>
                    </div>
                <?php endif; ?>
                <?php if(!$this->authService()->hasIdentity() && $service->isEdited()): ?>
                    <div class="row">
                        <div class="alert-box info" data-alert>
                            Please login, if you wish to save this collection permanently
                            <a class="close" href="#">&times;</a>
                        </div>
                    </div>
                <?php endif; ?>
                <?php if(!count($collection)): ?>
                    <div data-alert class="alert-box info">
                        Your active collection is empty.
                        <a href="#" class="close">&times;</a>
                    </div>
                <?php endif; ?>
                    <div class="row"  style="margin-bottom:2em;">
                        <div class="large-12 columns">
                            <ul id="collection" style="max-height: 300px; overflow-y: scroll; border:1px solid #eee;" >
                                <?php
                                $this->partialLoop()->setObjectKey('article');
                                echo $this->partialLoop('partials/article-list', $collection->getArticles());
                                ?>
                            </ul>
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-12 columns">
                            <ul class="button-group right">
                                <?php if(count($collection)): ?>
                                <li><a class="button tiny" href="#"><i class="fa fa-list-ol"></i>&nbsp; Export</a></li>
                                <?php endif; ?>
                                <?php if($this->authService()->hasIdentity()): ?>
                                <li><button type="submit" class="button tiny"><i class="fa fa-save"></i>&nbsp; Save</button></li>
                                    <?php if($collection->getId()): ?>
                                <li><a class="button tiny" data-reveal-id="delete-modal" href="<?php echo $this->url('collection/delete') . '?redirect=' . $_SERVER['REQUEST_URI']; ?>"><i class="fa fa-trash-o"></i>&nbsp; Delete</a>
                                    <div id="delete-modal" class="reveal-modal small" data-reveal>
                                        <h2>Delete collection</h2>
                                        <p>Are you sure? Do you want to delete the collection <?php echo $collection->getName(); ?>?</p>
                                        <a href="<?php echo $this->url('collection/delete') . '?redirect=' . $_SERVER['REQUEST_URI']; ?>"
                                           class="tiny button"><i class="fa fa-trash-o"></i>&nbsp; Delete <?php echo $collection->getName(); ?></a>
                                        <a class="close-reveal-modal">&#215;</a>
                                    </div>
                                </li>

                                    <?php endif; ?>
                                <?php endif; ?>
                            </ul>
                        </div>
                    </div>
                <?php if($this->authService()->hasIdentity()): ?>
                </form>
                <?php endif; ?>
            </aside>