                                    <?php
                                        $removeUrl = $this->url(
                                            'active-collection/remove',
                                            array(
                                                'id' => $article->getId()
                                            )
                                        );
                                        $removeUrl .= '?redirect=' . urlencode($_SERVER['REQUEST_URI']);
                                    ?>
                                    <li><?php echo $article->getTitle(); ?>
                                        <a class="remove" href="<?php echo $removeUrl; ?>">
                                           Remove
                                        </a>
                                    </li>