    <?php $article = $this->article; ?>
    <article>
        <header>
            <h3><?php echo $article->getTitle(); ?></h2>
            <h4><?php echo $this->authors($article->getAuthors())->render(); ?></h3>
        </header>
        <p><?php echo $this->abstract($article->getAbstract())->renderTruncated(); ?></p>
        <blockquote><?php echo $this->citation($article); ?></blockquote>
        <footer class="clearfix">
            <?php
                $pmid = substr($article->getIndexerId(), 4);
            ?>
            <ul class="button-group right">
                <li><a class="button tiny" target="_blank"
                       href="http://www.ncbi.nlm.nih.gov/pubmed/<?php echo $pmid; ?>"><i class="fa fa-external-link"></i>&nbsp; View in Pubmed</a></li>
                <li><a class="button tiny" href="<?php echo $this->url('active-collection/add', array('id' => $article->getId())) . '?redirect=' . urlencode($_SERVER['REQUEST_URI']); ?>"><i class="fa fa-plus"></i>&nbsp; Add to collection</a></li>

            </ul>
        </footer>
    </article>