<?php
    /** @var User\Entity\User $user */
    $user = $this->user;
?>
<h1>User profile</h1>
<table>
    <tr>
        <td>First name</td>
        <td><?php echo $user->getFirstName(); ?></td>
    </tr>
    <tr>
        <td>Last name</td>
        <td><?php echo $user->getLastName(); ?></td>
    </tr>
    <tr>
        <td>Name</td>
        <td><?php echo $user->getName(); ?></td>
    </tr>
    <tr>
        <td>Email</td>
        <td><?php echo $user->getEmail(); ?></td>
    </tr>
</table>
<?php $logoutUrl = $this->url('user/logout'); ?>
<p><a href="<?php echo $logoutUrl; ?>">Logout</a></p>