            <div class="row">
                <div class="small-12">
                    <h2>Overview</h2>
                </div>
            </div>
            <div class="row" data-equalizer>
                <div class="medium-6 columns">
                    <div class="panel clearfix" data-equalizer-watch>
                        <div class="row">
                            <div class="small-12 columns">
                                <h3>Users</h3>
                            </div>
                        </div>
                        <div class="row">
                            <div class="small-4 columns">
                                <p><b>Total Users</b></p>
                            </div>
                            <div class="small-8 columns">
                                <p><?php echo $totalUsers; ?></p>
                            </div>
                        </div>
                        <!--
                        <div class="row">
                            <div class="small-12 columns">
                                <h4>New Users</h4>
                            </div>
                        </div>
                        <div class="row">
                            <div class="small-4 columns">
                                <p><b>Last Day</b></p>
                            </div>
                            <div class="small-8 columns">
                                <p>2</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="small-4 columns">
                                <p><b>Last Month</b></p>
                            </div>
                            <div class="small-8 columns">
                                <p>100</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="small-4 columns">
                                <p><b>Last Year</b></p>
                            </div>
                            <div class="small-8 columns">
                                <p>273</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="small-12 columns">
                                <h4>Users logged in</h4>
                            </div>
                        </div>
                        <div class="row">
                            <div class="small-4 columns">
                                <p><b>Last Day</b></p>
                            </div>
                            <div class="small-8 columns">
                                <p>3</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="small-4 columns">
                                <p><b>Last Month</b></p>
                            </div>
                            <div class="small-8 columns">
                                <p>40</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="small-4 columns">
                                <p><b>Last Year</b></p>
                            </div>
                            <div class="small-8 columns">
                                <p>173</p>
                            </div>
                        </div>
                        -->
                        <a href="<?php echo $this->url('admin/users'); ?>" class="tiny button right"><span class="fa fa-arrow-circle-o-right"></span> View more</a>
                    </div>
                </div>
                <div class="medium-6 columns">
                    <div class="panel"  data-equalizer-watch>
                        <div class="row">
                            <div class="small-12 columns">
                                <h3>Collections</h3>
                            </div>
                        </div>
                        <div class="row">
                            <div class="small-4 columns">
                                <p><b>Total</b></p>
                            </div>
                            <div class="small-8 columns">
                                <p><?php echo $this->totalCollections; ?></p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="small-4 columns">
                                <p><b>Per user</b></p>
                            </div>
                            <div class="small-8 columns">
                                <p><?php echo ($this->totalCollections/$this->totalUsers); ?></p>
                            </div>
                        </div>
                        <!--
                        <div class="row">
                            <div class="small-12 columns">
                                <h4>Collections created</h4>
                            </div>
                        </div>
                        <div class="row">
                            <div class="small-4 columns">
                                <p><b>Last Day</b></p>
                            </div>
                            <div class="small-8 columns">
                                <p>2</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="small-4 columns">
                                <p><b>Last Month</b></p>
                            </div>
                            <div class="small-8 columns">
                                <p>100</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="small-4 columns">
                                <p><b>Last Year</b></p>
                            </div>
                            <div class="small-8 columns">
                                <p>273</p>
                            </div>
                        </div>
                        -->
                    </div>
                </div>
            </div>
            <div class="row" data-equalizer>
                <div class="medium-6 columns">
                    <div class="panel" data-equalizer-watch>
                        <div class="row">
                            <div class="small-12 columns">
                                <h3>Articles</h3>
                            </div>
                        </div>
                        <div class="row">
                            <div class="small-4 columns">
                                <p><b>Total</b></p>
                            </div>
                            <div class="small-8 columns">
                                <p><?php echo $this->totalArticles; ?></p>
                            </div>
                        </div>
                        <!--
                        <div class="row">
                            <div class="small-4 columns">
                                <p><b>Orphaned</b></p>
                            </div>
                            <div class="small-8 columns">
                                <p>5100</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="small-12 columns">
                                <h4>Articles created</h4>
                            </div>
                        </div>
                        <div class="row">
                            <div class="small-4 columns">
                                <p><b>Last Day</b></p>
                            </div>
                            <div class="small-8 columns">
                                <p>1002</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="small-4 columns">
                                <p><b>Last Month</b></p>
                            </div>
                            <div class="small-8 columns">
                                <p>2100</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="small-4 columns">
                                <p><b>Last Year</b></p>
                            </div>
                            <div class="small-8 columns">
                                <p>5100</p>
                            </div>
                        </div>
                        -->
                    </div>
                </div>
                <div class="medium-6 columns" >
                    <div class="panel callout clearfix" data-equalizer-watch>
                        <div class="row">
                            <div class="small-12 columns">
                                <h3>Exceptions</h3>
                            </div>
                        </div>
                        <div class="row">
                            <div class="small-4 columns">
                                <p><b>Total</b></p>
                            </div>
                            <div class="small-8 columns">
                                <p><?php echo $this->totalExceptions; ?></p>
                            </div>
                        </div>
                        <!--
                        <div class="row">
                            <div class="small-4 columns">
                                <p><b>Last Day</b></p>
                            </div>
                            <div class="small-8 columns">
                                <p>1002</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="small-4 columns">
                                <p><b>Last Week</b></p>
                            </div>
                            <div class="small-8 columns">
                                <p>2100</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="small-4 columns">
                                <p><b>Last Month</b></p>
                            </div>
                            <div class="small-8 columns">
                                <p>5100</p>
                            </div>
                        </div>
                        -->
                        <a href="<?php echo $this->url('admin/exceptions'); ?>" class="tiny button right"><span class="fa fa-arrow-circle-o-right"></span> View more</a>
                    </div>
                </div>
            </div>