<div class="large-8 columns" style="background:#fdfdfd;border:1px solid #ddd;border-radius:15px; padding-left:0px;margin:0px 0px 30px 0px;">
    <ul class="tabs" data-tab>
        <li class="tab-title active"><a href="#website-content" style="background:#faa900; color:#fff;border-top-left-radius:15px;">Website</a></li>
        <li class="tab-title"><a href="#book-content">Book</a></li>
        <li class="tab-title"><a href="#newspaper-content">Newspaper</a></li>
        <li class="tab-title"><a href="#journal-content">Journal</a></li>
        <li class="tab-title"><a href="#magaz-content" style="border-top-right-radius: 15px;">Magazine</a></li>
    </ul>

    <div id="tabs-header" style="background: #faa900; height:50px; padding:10px 10px 10px; text-align: center;">
        <h5 style="color:#fff;">Enter the Article, Website url and Author</h5>
    </div>

    <div class="tabs-content">

        <!-- Website cite styles -->

        <div class="content active" id="website-content">
               <form method="post" action="">
                   <div class="row">
                       <div class="small-4 columns">
                           <label for="webarticle-title" class="inline right">Article title</label>
                       </div>

                       <div class="small-8 columns">
                           <input type="text" name="webarticle-title" id="webarticle-title" value=""/>
                       </div>
                   </div>

                   <div class="row">
                       <div class="small-4 columns">
                           <label for="web-name" class="inline right">Website name</label>
                       </div>

                       <div class="small-8 columns">
                           <input type="text" name="web-name" id="web-name" value=""/>
                       </div>
                   </div>

                   <div class="row">
                       <div class="small-4 columns">
                           <label for="web-url" class="inline right">Website URL</label>
                       </div>

                       <div class="small-8 columns">
                           <input type="text" name="web-url" id="web-url" value=""/>
                       </div>
                   </div>

                   <fieldset>
                       <legend>Authors list</legend>
                        <div class="row">
                           <div class="small-2 columns">
                               <label for="author1" class="inline right">Author 1</label>
                           </div>
                           <div class="small-4 columns">
                               <input type="text" name="author1" class="author1" value=""/>
                           </div>

                           <div class="small-2 columns">
                               <label for="author2" class="inline right">Author 2</label>
                           </div>

                           <div class="small-4 columns">
                               <input type="text" name="author2" class="author2" value=""/>
                           </div>
                        </div>
                        <div class="row">
                           <div class="small-2 columns">
                               <label for="author3" class="inline right">Author 3</label>
                           </div>
                           <div class="small-4 columns">
                               <input type="text" name="author3" class="author3" value=""/>
                           </div>

                           <div class="small-2 columns">
                               <label for="author4" class="inline right">Author 4</label>
                           </div>
                           <div class="small-4 columns">
                               <input type="text" name="author4" class="author4" value=""/>
                           </div>
                        </div>

                        <div class="row">
                           <div class="small-2 columns">
                               <label for="author5" class="inline right">Author 5</label>
                           </div>
                           <div class="small-4 columns">
                               <input type="text" name="author5" class="author5" value=""/>
                           </div>

                           <div class="small-2 columns">
                               <label for="author6" class="inline right">Author 6</label>
                           </div>

                           <div class="small-4 columns">
                               <input type="text" name="author6" class="author6" value=""/>
                           </div>
                        </div>
                       </fieldset>




                   <div class="row">
                           <div class="small-4 columns">
                               <label for="date-pub" class="inline right">Date published</label>
                           </div>
                           <div class="small-4 columns">
                               <select class="inline right">
                                   <option>Month</option>
                                   <option>January</option>
                                   <option>February</option>
                                   <option>March</option>
                                   <option>April</option>
                                   <option>May</option>
                                   <option>June</option>
                                   <option>July</option>
                                   <option>August</option>
                                   <option>September</option>
                                   <option>October</option>
                                   <option>November</option>
                                   <option>December</option>
                               </select>
                           </div>

                           <div class="small-4 columns">
                               <select class="inline right">
                                   <option>Year</option>
                                   <option>2014</option>
                                   <option>2013</option>
                                   <option>2012</option>
                                   <option>2011</option>
                                   <option>2010</option>
                                   <option>2009</option>
                                   <option>2008</option>
                                   <option>2007</option>
                                   <option>2006</option>
                                   <option>2005</option>
                                   <option>2004</option>
                                   <option>2003</option>
                                   <option>2002</option>
                                   <option>2001</option>
                                   <option>2000</option>
                                   <option>1999</option>
                                   <option>1998</option>
                                   <option>1997</option>
                                   <option>1996</option>
                                   <option>1995</option>
                                   <option>1994</option>
                                   <option>1993</option>
                                   <option>1992</option>
                                   <option>1991</option>
                                   <option>1990</option>
                                   <option>1989</option>
                                   <option>1988</option>
                                   <option>1987</option>
                                   <option>1986</option>
                                   <option>1985</option>
                                   <option>1984</option>
                                   <option>1983</option>
                                   <option>1982</option>
                                   <option>1981</option>
                                   <option>1980</option>
                                   <option>1979</option>
                                   <option>1978</option>
                                   <option>1977</option>
                                   <option>1976</option>
                                   <option>1975</option>
                                   <option>1974</option>
                                   <option>1973</option>
                                   <option>1972</option>
                                   <option>1971</option>
                                   <option>1970</option>
                                   <option>1969</option>
                                   <option>1968</option>
                                   <option>1967</option>
                                   <option>1966</option>
                                   <option>1965</option>
                                   <option>1964</option>
                                   <option>1963</option>
                                   <option>1962</option>
                                   <option>1961</option>
                                   <option>1960</option>
                                   <option>1959</option>
                                   <option>1958</option>
                                   <option>1957</option>
                                   <option>1956</option>
                                   <option>1955</option>
                                   <option>1954</option>
                                   <option>1953</option>
                                   <option>1952</option>
                                   <option>1951</option>
                                   <option>1950</option>
                                   <option>1949</option>
                                   <option>1948</option>
                                   <option>1947</option>
                                   <option>1946</option>
                                   <option>1945</option>
                               </select>
                           </div>
                   </div>


                   <div class="row">
                       <div class="small-4 columns">
                           <label for="date-acc" class="inline right">Date accessed</label>
                       </div>
                       <div class="small-4 columns">
                           <select class="inline right">
                               <option>Month</option>
                               <option>January</option>
                               <option>February</option>
                               <option>March</option>
                               <option>April</option>
                               <option>May</option>
                               <option>June</option>
                               <option>July</option>
                               <option>August</option>
                               <option>September</option>
                               <option>October</option>
                               <option>November</option>
                               <option>December</option>
                           </select>
                       </div>

                       <div class="small-4 columns">
                           <select class="inline right">
                               <option>Year</option>
                               <option>2014</option>
                               <option>2013</option>
                               <option>2012</option>
                               <option>2011</option>
                               <option>2010</option>
                               <option>2009</option>
                               <option>2008</option>
                               <option>2007</option>
                               <option>2006</option>
                               <option>2005</option>
                               <option>2004</option>
                               <option>2003</option>
                               <option>2002</option>
                               <option>2001</option>
                               <option>2000</option>
                               <option>1999</option>
                               <option>1998</option>
                               <option>1997</option>
                               <option>1996</option>
                               <option>1995</option>
                               <option>1994</option>
                               <option>1993</option>
                               <option>1992</option>
                               <option>1991</option>
                               <option>1990</option>
                               <option>1989</option>
                               <option>1988</option>
                               <option>1987</option>
                               <option>1986</option>
                               <option>1985</option>
                               <option>1984</option>
                               <option>1983</option>
                               <option>1982</option>
                               <option>1981</option>
                               <option>1980</option>
                               <option>1979</option>
                               <option>1978</option>
                               <option>1977</option>
                               <option>1976</option>
                               <option>1975</option>
                               <option>1974</option>
                               <option>1973</option>
                               <option>1972</option>
                               <option>1971</option>
                               <option>1970</option>
                               <option>1969</option>
                               <option>1968</option>
                               <option>1967</option>
                               <option>1966</option>
                               <option>1965</option>
                               <option>1964</option>
                               <option>1963</option>
                               <option>1962</option>
                               <option>1961</option>
                               <option>1960</option>
                               <option>1959</option>
                               <option>1958</option>
                               <option>1957</option>
                               <option>1956</option>
                               <option>1955</option>
                               <option>1954</option>
                               <option>1953</option>
                               <option>1952</option>
                               <option>1951</option>
                               <option>1950</option>
                               <option>1949</option>
                               <option>1948</option>
                               <option>1947</option>
                               <option>1946</option>
                               <option>1945</option>
                           </select>
                       </div>
                   </div>


               </form>

        </div>

        <!-- Book cite styles -->

        <div class="content" id="book-content">
            <form method="post" action="">
                <div class="row">
                    <div class="small-4 columns">
                        <label for="book-title" class="inline right">Book title</label>
                    </div>

                    <div class="small-8 columns">
                        <input type="text" name="book-title" id="book-title" value=""/>
                    </div>
                </div>

                <div class="row">
                    <div class="small-4 columns">
                        <label for="publisher-name" class="inline right">Publisher</label>
                    </div>

                    <div class="small-8 columns">
                        <input type="text" name="publisher-name" id="publisher-name" value=""/>
                    </div>
                </div>

                <div class="row">
                    <div class="small-4 columns">
                        <label for="publishing-city" class="inline right">Publishing city</label>
                    </div>

                    <div class="small-8 columns">
                        <input type="text" name="publishing-city" id="publishing-city" value=""/>
                    </div>
                </div>

                <div class="row">
                    <div class="small-4 columns">
                        <label for="volume" class="inline right">Volume</label>
                    </div>

                    <div class="small-2 columns">
                        <input type="text" name="volume" id="volume" value=""/>
                    </div>

                    <div class="small-4 columns">
                        <label for="pages" class="inline right">Pages</label>
                    </div>

                    <div class="small-2 columns">
                        <input type="text" name="pages" id="pages" value=""/>
                    </div>
                </div>


                <div class="row">
                    <div class="small-4 columns">
                        <label for="series" class="inline right">Series</label>
                    </div>

                    <div class="small-2 columns">
                        <input type="text" name="series" id="series" value=""/>
                    </div>

                    <div class="small-4 columns">
                        <label for="edition" class="inline right">Edition</label>
                    </div>

                    <div class="small-2 columns">
                        <input type="text" name="edition" id="edition" value=""/>
                    </div>
                </div>

                <div class="row">
                    <div class="small-4 columns">
                        <label for="year-published" class="inline right">Year published</label>
                    </div>

                    <div class="small-8 columns">
                        <select class="inline right">
                            <option>Year</option>
                            <option>2014</option>
                            <option>2013</option>
                            <option>2012</option>
                            <option>2011</option>
                            <option>2010</option>
                            <option>2009</option>
                            <option>2008</option>
                            <option>2007</option>
                            <option>2006</option>
                            <option>2005</option>
                            <option>2004</option>
                            <option>2003</option>
                            <option>2002</option>
                            <option>2001</option>
                            <option>2000</option>
                            <option>1999</option>
                            <option>1998</option>
                            <option>1997</option>
                            <option>1996</option>
                            <option>1995</option>
                            <option>1994</option>
                            <option>1993</option>
                            <option>1992</option>
                            <option>1991</option>
                            <option>1990</option>
                            <option>1989</option>
                            <option>1988</option>
                            <option>1987</option>
                            <option>1986</option>
                            <option>1985</option>
                            <option>1984</option>
                            <option>1983</option>
                            <option>1982</option>
                            <option>1981</option>
                            <option>1980</option>
                            <option>1979</option>
                            <option>1978</option>
                            <option>1977</option>
                            <option>1976</option>
                            <option>1975</option>
                            <option>1974</option>
                            <option>1973</option>
                            <option>1972</option>
                            <option>1971</option>
                            <option>1970</option>
                            <option>1969</option>
                            <option>1968</option>
                            <option>1967</option>
                            <option>1966</option>
                            <option>1965</option>
                            <option>1964</option>
                            <option>1963</option>
                            <option>1962</option>
                            <option>1961</option>
                            <option>1960</option>
                            <option>1959</option>
                            <option>1958</option>
                            <option>1957</option>
                            <option>1956</option>
                            <option>1955</option>
                            <option>1954</option>
                            <option>1953</option>
                            <option>1952</option>
                            <option>1951</option>
                            <option>1950</option>
                            <option>1949</option>
                            <option>1948</option>
                            <option>1947</option>
                            <option>1946</option>
                            <option>1945</option>
                        </select>
                    </div>
                </div>
            </form>
        </div>

        <!-- Newspaper cite styles -->

        <div class="content" id="newspaper-content">
            <form method="post" action="">
                <div class="row">
                    <div class="small-4 columns">
                        <label for="newspaper-article" class="inline right">Article article</label>
                    </div>
                    <div class="small-8 columns">
                        <input type="text" name="newspaper-article" id="newspaper-article" value=""/>
                    </div>
                </div>

                <div class="row">
                    <div class="small-4 columns">
                        <label for="newspaper-title" class="inline right">Newspaper title</label>
                    </div>
                    <div class="small-8 columns">
                        <input type="text" name="newspaper-title" id="newspaper-title" value=""/>
                    </div>
                </div>

                <div class="row">
                    <div class="small-4 columns">
                        <label for="date-published" class="inline right">Date Published</label>
                    </div>
                    <div class="small-2 columns">
                        <input type="text" name="day-published" id="day-published" value="dd"/>
                    </div>
                    <div class="small-3 columns">
                        <input type="text" name="month-published" id="month-published" value="mm"/>
                    </div>
                    <div class="small-3 columns">
                        <input type="text" name="year-published" id="year-published" value="yyyy"/>
                    </div>
                </div>

                    <div class="row">
                        <div class="small-4 columns">
                            <label for="city-published" class="inline right">City published</label>
                        </div>

                        <div class="small-8 columns">
                            <input type="text" name="city-published" id="city-published" value=""/>
                        </div>
                    </div>

                <fieldset>
                    <legend>Authors list</legend>
                    <div class="row">
                        <div class="small-2 columns">
                            <label for="author1" class="inline right">Author 1</label>
                        </div>
                        <div class="small-4 columns">
                            <input type="text" name="author1" class="author1" value=""/>
                        </div>

                        <div class="small-2 columns">
                            <label for="author2" class="inline right">Author 2</label>
                        </div>

                        <div class="small-4 columns">
                            <input type="text" name="author2" class="author2" value=""/>
                        </div>
                    </div>
                    <div class="row">
                        <div class="small-2 columns">
                            <label for="author3" class="inline right">Author 3</label>
                        </div>
                        <div class="small-4 columns">
                            <input type="text" name="author3" class="author3" value=""/>
                        </div>

                        <div class="small-2 columns">
                            <label for="author4" class="inline right">Author 4</label>
                        </div>
                        <div class="small-4 columns">
                            <input type="text" name="author4" class="author4" value=""/>
                        </div>
                    </div>

                    <div class="row">
                        <div class="small-2 columns">
                            <label for="author5" class="inline right">Author 5</label>
                        </div>
                        <div class="small-4 columns">
                            <input type="text" name="author5" class="author5" value=""/>
                        </div>

                        <div class="small-2 columns">
                            <label for="author6" class="inline right">Author 6</label>
                        </div>

                        <div class="small-4 columns">
                            <input type="text" name="author6" class="author6" value=""/>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>

        <!-- Journal cite styles -->

        <div class="content" id="journal-content">
            <form method="post" action="">
                <div class="row">
                    <div class="small-4 columns">
                        <label for="journarticle-title" class="inline right">Article title</label>
                    </div>

                    <div class="small-8 columns">
                        <input type="text" name="journarticle-title" id="journarticle-title" value=""/>
                    </div>
                </div>

                <div class="row">
                    <div class="small-4 columns">
                        <label for="journal-title" class="inline right">Journal title</label>
                    </div>

                    <div class="small-8 columns">
                        <input type="text" name="journal-title" id="journal-title" value=""/>
                    </div>
                </div>

                <div class="row">
                    <div class="small-4 columns">
                        <label for="volume" class="inline right">Volume</label>
                    </div>

                    <div class="small-8 columns">
                        <input type="text" name="volume" id="volume" value=""/>
                    </div>
                </div>

                <div class="row">
                    <div class="small-4 columns">
                        <label for="issue" class="inline right">Issue</label>
                    </div>

                    <div class="small-8 columns">
                        <input type="text" name="issue" id="issue" value=""/>
                    </div>
                </div>

                <div class="row">
                    <div class="small-4 columns">
                        <label for="pages" class="inline right">Pages</label>
                    </div>

                    <div class="small-8 columns">
                        <input type="text" name="pages" id="pages" value=""/>
                    </div>
                </div>
                <fieldset>
                <legend>Authors list</legend>
                <div class="row">
                    <div class="small-2 columns">
                        <label for="author1" class="inline right">Author 1</label>
                    </div>
                    <div class="small-4 columns">
                        <input type="text" name="author1" class="author1" value=""/>
                    </div>
                    <div class="small-2 columns">
                        <label for="author2" class="inline right">Author 2</label>
                    </div>
                    <div class="small-4 columns">
                        <input type="text" name="author2" class="author2" value=""/>
                    </div>
                </div>

                <div class="row">
                    <div class="small-2 columns">
                        <label for="author3" class="inline right">Author 3</label>
                    </div>
                    <div class="small-4 columns">
                        <input type="text" name="author3" class="author3" value=""/>
                    </div>
                    <div class="small-2 columns">
                        <label for="author4" class="inline right">Author 4</label>
                    </div>
                    <div class="small-4 columns">
                        <input type="text" name="author4" class="author4" value=""/>
                    </div>
                </div>

                <div class="row">
                    <div class="small-2 columns">
                        <label for="author5" class="inline right">Author 5</label>
                    </div>
                    <div class="small-4 columns">
                        <input type="text" name="author5" class="author5" value=""/>
                    </div>
                    <div class="small-2 columns">
                        <label for="author6" class="inline right">Author 6</label>
                    </div>
                    <div class="small-4 columns">
                        <input type="text" name="author6" class="author6" value=""/>
                    </div>
                </div>
                </fieldset>

                <div class="row">
                    <div class="small-4 columns">
                        <label for="date-pub" class="inline right">Date published</label>
                    </div>
                    <div class="small-4 columns">
                        <select class="inline right">
                            <option>Month</option>
                            <option>January</option>
                            <option>February</option>
                            <option>March</option>
                            <option>April</option>
                            <option>May</option>
                            <option>June</option>
                            <option>July</option>
                            <option>August</option>
                            <option>September</option>
                            <option>October</option>
                            <option>November</option>
                            <option>December</option>
                        </select>
                    </div>

                    <div class="small-4 columns">
                        <select class="inline right">
                            <option>Year</option>
                            <option>2014</option>
                            <option>2013</option>
                            <option>2012</option>
                            <option>2011</option>
                            <option>2010</option>
                            <option>2009</option>
                            <option>2008</option>
                            <option>2007</option>
                            <option>2006</option>
                            <option>2005</option>
                            <option>2004</option>
                            <option>2003</option>
                            <option>2002</option>
                            <option>2001</option>
                            <option>2000</option>
                            <option>1999</option>
                            <option>1998</option>
                            <option>1997</option>
                            <option>1996</option>
                            <option>1995</option>
                            <option>1994</option>
                            <option>1993</option>
                            <option>1992</option>
                            <option>1991</option>
                            <option>1990</option>
                            <option>1989</option>
                            <option>1988</option>
                            <option>1987</option>
                            <option>1986</option>
                            <option>1985</option>
                            <option>1984</option>
                            <option>1983</option>
                            <option>1982</option>
                            <option>1981</option>
                            <option>1980</option>
                            <option>1979</option>
                            <option>1978</option>
                            <option>1977</option>
                            <option>1976</option>
                            <option>1975</option>
                            <option>1974</option>
                            <option>1973</option>
                            <option>1972</option>
                            <option>1971</option>
                            <option>1970</option>
                            <option>1969</option>
                            <option>1968</option>
                            <option>1967</option>
                            <option>1966</option>
                            <option>1965</option>
                            <option>1964</option>
                            <option>1963</option>
                            <option>1962</option>
                            <option>1961</option>
                            <option>1960</option>
                            <option>1959</option>
                            <option>1958</option>
                            <option>1957</option>
                            <option>1956</option>
                            <option>1955</option>
                            <option>1954</option>
                            <option>1953</option>
                            <option>1952</option>
                            <option>1951</option>
                            <option>1950</option>
                            <option>1949</option>
                            <option>1948</option>
                            <option>1947</option>
                            <option>1946</option>
                            <option>1945</option>
                        </select>
                    </div>
                </div>

                <div class="row">
                    <div class="small-4 columns">
                        <label for="date-acc" class="inline right">Date accessed</label>
                    </div>
                    <div class="small-4 columns">
                        <select class="inline right">
                            <option>Month</option>
                            <option>January</option>
                            <option>February</option>
                            <option>March</option>
                            <option>April</option>
                            <option>May</option>
                            <option>June</option>
                            <option>July</option>
                            <option>August</option>
                            <option>September</option>
                            <option>October</option>
                            <option>November</option>
                            <option>December</option>
                        </select>
                    </div>

                    <div class="small-4 columns">
                        <select class="inline right">
                            <option>Year</option>
                            <option>2014</option>
                            <option>2013</option>
                            <option>2012</option>
                            <option>2011</option>
                            <option>2010</option>
                            <option>2009</option>
                            <option>2008</option>
                            <option>2007</option>
                            <option>2006</option>
                            <option>2005</option>
                            <option>2004</option>
                            <option>2003</option>
                            <option>2002</option>
                            <option>2001</option>
                            <option>2000</option>
                            <option>1999</option>
                            <option>1998</option>
                            <option>1997</option>
                            <option>1996</option>
                            <option>1995</option>
                            <option>1994</option>
                            <option>1993</option>
                            <option>1992</option>
                            <option>1991</option>
                            <option>1990</option>
                            <option>1989</option>
                            <option>1988</option>
                            <option>1987</option>
                            <option>1986</option>
                            <option>1985</option>
                            <option>1984</option>
                            <option>1983</option>
                            <option>1982</option>
                            <option>1981</option>
                            <option>1980</option>
                            <option>1979</option>
                            <option>1978</option>
                            <option>1977</option>
                            <option>1976</option>
                            <option>1975</option>
                            <option>1974</option>
                            <option>1973</option>
                            <option>1972</option>
                            <option>1971</option>
                            <option>1970</option>
                            <option>1969</option>
                            <option>1968</option>
                            <option>1967</option>
                            <option>1966</option>
                            <option>1965</option>
                            <option>1964</option>
                            <option>1963</option>
                            <option>1962</option>
                            <option>1961</option>
                            <option>1960</option>
                            <option>1959</option>
                            <option>1958</option>
                            <option>1957</option>
                            <option>1956</option>
                            <option>1955</option>
                            <option>1954</option>
                            <option>1953</option>
                            <option>1952</option>
                            <option>1951</option>
                            <option>1950</option>
                            <option>1949</option>
                            <option>1948</option>
                            <option>1947</option>
                            <option>1946</option>
                            <option>1945</option>
                        </select>
                    </div>
                </div>


            </form>

        </div>

        <!-- Magazine cite styles -->

        <div class="content" id="magaz-content">
                <form method="post" action="">
                    <div class="row">
                        <div class="small-4 columns">
                            <label for="magzarticle-title" class="inline right">Article title</label>
                        </div>

                        <div class="small-8 columns">
                            <input type="text" name="magzarticle-title" id="magzarticle-title" value=""/>
                        </div>
                    </div>

                    <div class="row">
                        <div class="small-4 columns">
                            <label for="magazine-title" class="inline right">Magazine title</label>
                        </div>

                        <div class="small-8 columns">
                            <input type="text" name="magazine-title" id="magazine-title" value=""/>
                        </div>
                    </div>

                    <div class="row">
                        <div class="small-4 columns">
                            <label for="magz-issue" class="inline right">Issue</label>
                        </div>

                        <div class="small-8 columns">
                            <input type="text" name="magz-issue" id="magz-issue" value=""/>
                        </div>
                    </div>

                    <div class="row">
                        <div class="small-4 columns">
                            <label for="magz-volume" class="inline right">Volume</label>
                        </div>

                        <div class="small-8 columns">
                            <input type="text" name="magz-volume" id="magz-volume" value=""/>
                        </div>
                    </div>

                    <div class="row">
                        <div class="small-4 columns">
                            <label for="magz-pages" class="inline right">Pages</label>
                        </div>

                        <div class="small-8 columns">
                            <input type="text" name="magz-pages" id="magz-pages" value=""/>
                        </div>
                    </div>


                    <fieldset>
                        <legend>Authors list</legend>
                        <div class="row">
                            <div class="small-2 columns">
                                <label for="author1" class="inline right">Author 1</label>
                            </div>
                            <div class="small-4 columns">
                                <input type="text" name="author1" class="author1" value=""/>
                            </div>

                            <div class="small-2 columns">
                                <label for="author2" class="inline right">Author 2</label>
                            </div>

                            <div class="small-4 columns">
                                <input type="text" name="author2" class="author2" value=""/>
                            </div>
                        </div>
                        <div class="row">
                            <div class="small-2 columns">
                                <label for="author3" class="inline right">Author 3</label>
                            </div>
                            <div class="small-4 columns">
                                <input type="text" name="author3" class="author3" value=""/>
                            </div>

                            <div class="small-2 columns">
                                <label for="author4" class="inline right">Author 4</label>
                            </div>
                            <div class="small-4 columns">
                                <input type="text" name="author4" class="author4" value=""/>
                            </div>
                        </div>

                        <div class="row">
                            <div class="small-2 columns">
                                <label for="author5" class="inline right">Author 5</label>
                            </div>
                            <div class="small-4 columns">
                                <input type="text" name="author5" class="author5" value=""/>
                            </div>

                            <div class="small-2 columns">
                                <label for="author6" class="inline right">Author 6</label>
                            </div>

                            <div class="small-4 columns">
                                <input type="text" name="author6" class="author6" value=""/>
                            </div>
                        </div>
                    </fieldset>

                        <div class="row">
                            <div class="small-4 columns">
                                <label for="date-pub" class="inline right">Date published</label>
                            </div>
                            <div class="small-4 columns">
                                <select class="inline right">
                                    <option>Month</option>
                                    <option>January</option>
                                    <option>February</option>
                                    <option>March</option>
                                    <option>April</option>
                                    <option>May</option>
                                    <option>June</option>
                                    <option>July</option>
                                    <option>August</option>
                                    <option>September</option>
                                    <option>October</option>
                                    <option>November</option>
                                    <option>December</option>
                                </select>
                            </div>

                            <div class="small-4 columns">
                                <select class="inline right">
                                    <option>Year</option>
                                    <option>2014</option>
                                    <option>2013</option>
                                    <option>2012</option>
                                    <option>2011</option>
                                    <option>2010</option>
                                    <option>2009</option>
                                    <option>2008</option>
                                    <option>2007</option>
                                    <option>2006</option>
                                    <option>2005</option>
                                    <option>2004</option>
                                    <option>2003</option>
                                    <option>2002</option>
                                    <option>2001</option>
                                    <option>2000</option>
                                    <option>1999</option>
                                    <option>1998</option>
                                    <option>1997</option>
                                    <option>1996</option>
                                    <option>1995</option>
                                    <option>1994</option>
                                    <option>1993</option>
                                    <option>1992</option>
                                    <option>1991</option>
                                    <option>1990</option>
                                    <option>1989</option>
                                    <option>1988</option>
                                    <option>1987</option>
                                    <option>1986</option>
                                    <option>1985</option>
                                    <option>1984</option>
                                    <option>1983</option>
                                    <option>1982</option>
                                    <option>1981</option>
                                    <option>1980</option>
                                    <option>1979</option>
                                    <option>1978</option>
                                    <option>1977</option>
                                    <option>1976</option>
                                    <option>1975</option>
                                    <option>1974</option>
                                    <option>1973</option>
                                    <option>1972</option>
                                    <option>1971</option>
                                    <option>1970</option>
                                    <option>1969</option>
                                    <option>1968</option>
                                    <option>1967</option>
                                    <option>1966</option>
                                    <option>1965</option>
                                    <option>1964</option>
                                    <option>1963</option>
                                    <option>1962</option>
                                    <option>1961</option>
                                    <option>1960</option>
                                    <option>1959</option>
                                    <option>1958</option>
                                    <option>1957</option>
                                    <option>1956</option>
                                    <option>1955</option>
                                    <option>1954</option>
                                    <option>1953</option>
                                    <option>1952</option>
                                    <option>1951</option>
                                    <option>1950</option>
                                    <option>1949</option>
                                    <option>1948</option>
                                    <option>1947</option>
                                    <option>1946</option>
                                    <option>1945</option>
                                </select>
                            </div>
                        </div>

                        <div class="row">
                            <div class="small-4 columns">
                                <label for="date-acc" class="inline right">Date accessed</label>
                            </div>
                            <div class="small-4 columns">
                                <select class="inline right">
                                    <option>Month</option>
                                    <option>January</option>
                                    <option>February</option>
                                    <option>March</option>
                                    <option>April</option>
                                    <option>May</option>
                                    <option>June</option>
                                    <option>July</option>
                                    <option>August</option>
                                    <option>September</option>
                                    <option>October</option>
                                    <option>November</option>
                                    <option>December</option>
                                </select>
                            </div>

                            <div class="small-4 columns">
                                <select class="inline right">
                                    <option>Year</option>
                                    <option>2014</option>
                                    <option>2013</option>
                                    <option>2012</option>
                                    <option>2011</option>
                                    <option>2010</option>
                                    <option>2009</option>
                                    <option>2008</option>
                                    <option>2007</option>
                                    <option>2006</option>
                                    <option>2005</option>
                                    <option>2004</option>
                                    <option>2003</option>
                                    <option>2002</option>
                                    <option>2001</option>
                                    <option>2000</option>
                                    <option>1999</option>
                                    <option>1998</option>
                                    <option>1997</option>
                                    <option>1996</option>
                                    <option>1995</option>
                                    <option>1994</option>
                                    <option>1993</option>
                                    <option>1992</option>
                                    <option>1991</option>
                                    <option>1990</option>
                                    <option>1989</option>
                                    <option>1988</option>
                                    <option>1987</option>
                                    <option>1986</option>
                                    <option>1985</option>
                                    <option>1984</option>
                                    <option>1983</option>
                                    <option>1982</option>
                                    <option>1981</option>
                                    <option>1980</option>
                                    <option>1979</option>
                                    <option>1978</option>
                                    <option>1977</option>
                                    <option>1976</option>
                                    <option>1975</option>
                                    <option>1974</option>
                                    <option>1973</option>
                                    <option>1972</option>
                                    <option>1971</option>
                                    <option>1970</option>
                                    <option>1969</option>
                                    <option>1968</option>
                                    <option>1967</option>
                                    <option>1966</option>
                                    <option>1965</option>
                                    <option>1964</option>
                                    <option>1963</option>
                                    <option>1962</option>
                                    <option>1961</option>
                                    <option>1960</option>
                                    <option>1959</option>
                                    <option>1958</option>
                                    <option>1957</option>
                                    <option>1956</option>
                                    <option>1955</option>
                                    <option>1954</option>
                                    <option>1953</option>
                                    <option>1952</option>
                                    <option>1951</option>
                                    <option>1950</option>
                                    <option>1949</option>
                                    <option>1948</option>
                                    <option>1947</option>
                                    <option>1946</option>
                                    <option>1945</option>
                                </select>
                            </div>
                        </div>
                </form>
        </div>
    </div>


    <div id="tabs-header" style="background: #faa900; height:56px; padding:14px 10px 10px; text-align: center;margin-bottom:10px;">
        <h5 style="color:#fff;">Enter the Citation Style</h5>
    </div>

    <div class="row">
        <div class="small-4 columns">
            <label for="citation-style" class="inline right">Citation style</label>
        </div>

        <div class="small-8 columns">
            <select class="inline right" style="border-radius:10px;">
                <option>Vancouver</option>
                <option>APA</option>
                <option>MLA</option>
                <option>Harvard</option>
                <option>Chicago</option>
                <option>Oxford</option>
                <option>IEEE</option>
                <option>CBE</option>
                <option>Cambridge</option>
                <option>Turabian</option>
            </select>
        </div>
        <div class="clearfix"></div>

        <div class="small-5 small-centered columns">
            <ul class="button-group center">
                <li><a class="button small" target="_blank" href="#">Get Citation</a></li>
                <li><a class="button small" href="#">Reset</a></li>

            </ul>
        </div>

    </div>
</div>
<div class="large-4 columns">
    <?php echo $this->activeCollection()->render(); ?>
</div>