<?php echo $this->doctype(); ?>
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Kivi '. $this->translate('Refgen'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/stylesheets/font-awesome.css')
                        ->prependStylesheet($this->basePath() . '/stylesheets/app.css')
                        ->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:400,700|Roboto+Slab:300')
        ; ?>


        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/bower_components/modernizr/modernizr.js');
        ?>
    </head>
    <body>
        <nav class="top-bar" data-topbar>
            <ul class="title-area">
                <li class="name">
                    <h1><a href="<?php echo $this->basePath() . $this->url('home'); ?>">Refgen</a></h1>
                </li>
                <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
            </ul>
            <section class="top-bar-section">
                <ul class="left">
                    <li class="divider"></li>
                    <li><a href="#"><i class="fa fa-info-circle"></i>&nbsp; About</a></li>
                    <?php if($this->hasAccess('Collection\Controller\Collection', 'new')): ?>
                    <li class="divider"></li>
                    <li class="has-dropdown"><a href="#"><i class="fa fa-list"></i>&nbsp; Collections</a>
                        <ul class="dropdown">
                            <li>
                            <?php if($this->activeCollection()->isEdited()): ?>
                                <a href="<?php echo $this->url('collection/new') . '?redirect=' . urlencode($_SERVER['REQUEST_URI']); ?>" data-reveal-id="new-modal">
                            <?php else: ?>
                                <a href="<?php echo $this->url('collection/new') . '?redirect=' . urlencode($_SERVER['REQUEST_URI']); ?>">
                            <?php endif; ?>
                                    <i class="fa fa-file"></i>&nbsp; New
                                </a>
                            </li>

                            <?php $recents = $this->collections()->recents(); ?>
                            <?php if(count($recents)): ?>
                            <li><a href="#"><i class="fa fa-folder-open"></i>&nbsp; Open</a></li>
                            <li class="divider"></li>
                            <li class="has-dropdown"><a href="#"><i class="fa fa-history"></i>&nbsp; Recents</a>
                            <ul class="dropdown">
                                <?php foreach($recents as $collection): ?>
                                <li>
                                <?php if($this->activeCollection()->isEdited()): ?>
                                    <a class="open-recent-modal" href="<?php echo $this->url('collection/open', array('id' => $collection['id'])) . '?redirect=' . urlencode($_SERVER['REQUEST_URI']); ?>">
                                <?php else: ?>
                                    <a href="<?php echo $this->url('collection/open', array('id' => $collection['id'])) . '?redirect=' . urlencode($_SERVER['REQUEST_URI']); ?>">
                                <?php endif; ?>
                                        <i class="fa fa-list-alt"></i>&nbsp; <?php echo $collection['name']; ?>
                                    </a>
                                </li>
                                <?php endforeach; ?>
                            </ul>
                            <?php endif; ?>
                            </li>
                        </ul>
                    </li>
                    <?php endif; ?>
                </ul>
                <ul class="right">
                    <?php if($this->authService()->hasIdentity()): ?>
                    <li class="has-dropdown">
                        <a href="#">
                            <img style="width:35px; height:35px; border:2px solid #fff; margin-right:10px;" src="<?php echo $this->authService()->getIdentity()->getPictureLink(); ?>"/>
                            <span><?php echo $this->authService()->getIdentity()->getFirstName(); ?></span>
                        </a>
                        <ul class="dropdown">
                            <li><a href="#"><i class="fa fa-user"></i>&nbsp; My Account</a></li>
                            <li>
                            <?php if($this->activeCollection()->isEdited()): ?>
                                <a href="<?php echo $this->url('user/logout'); ?>" data-reveal-id="logout-modal">
                            <?php else: ?>
                                <a href="<?php echo $this->url('user/logout'); ?>">
                            <?php endif; ?>
                                <i class="fa fa-sign-out"></i>&nbsp; Log out</a></li>
                        </ul>
                    </li>
                    <?php else: ?>
                    <li><a href="<?php echo $this->url('user/login') . '?redirect=' . urlencode($_SERVER['REQUEST_URI']); ?>"><i class="fa fa-sign-in"></i>&nbsp; Log in</a></li>
                    <?php endif; ?>
                    <li class="divider"></li>
                    <li class="has-form">
                        <form method="get" action="<?php echo $this->url('search'); ?>">
                            <div class="row collapse">
                                <div class="small-10 columns">
                                    <input type="search" name="term" id="txt-search" placeholder="Search via pubmed"/>
                                </div>
                                <div class="small-2 columns">
                                    <button type="submit" class="tiny button"><span class="fa fa-search"></span></button>
                                </div>
                            </div>

                        </form>
                    </li>

                </ul>
            </section>
        </nav>
        <div id="content">
            <div class="row">
                <?php
                    $flash = $this->flashMessenger();
                    $flash->setMessageOpenFormat('<div data-alert%s><a href="#" class="close">&times;</a>')
                          ->setMessageSeparatorString('<br/>')
                          ->setMessageCloseString('</div>');
                    echo $flash->render('error',   array('alert-box', 'alert'));
                    echo $flash->render('info',    array('alert-box', 'info'));
                    echo $flash->render('default', array('alert-box'));
                    echo $flash->render('success', array('alert-box', 'success'));
                ?>
            </div>
            <div class="row">
                <?php echo $this->content; ?>
            </div>
        </div>
        <footer id="page-footer">
            <div class="row">
                <div class="large-12 columns">
                    <p>&copy; 2013 - <?php echo date('Y') ?> by Kivi Designers. <?php echo $this->translate('All rights reserved.') ?></p>
                </div>
            </div>
        </footer>
        <div id="new-modal" class="reveal-modal small" data-reveal>
            <h2>New Collection</h2>
            <p class="lead">Your active collection is edited . If you wish to continue, unsaved changes will be lost</p>
            <a class="tiny button" href="<?php echo $this->url('collection/new'); ?>"><i class="fa fa-file"></i>&nbsp; New Collection</a>
            <a class="close-reveal-modal">&#215;</a>
        </div>
        <div id="recent-modal" class="reveal-modal small" data-reveal>
            <h2>Open Collection</h2>
            <p class="lead">Your active collection is edited . If you wish to continue, all unsaved changes will be lost</p>
            <a id='confirm-open-recent' class="tiny button" href=""><i class="fa fa-list-alt"></i>&nbsp; Open <span class="recent-collection-name"></span></a>
            <a class="close-reveal-modal">&#215;</a>
        </div>
        <div id="logout-modal" class="reveal-modal small" data-reveal>
            <h2>Logout</h2>
            <p class="lead">Your active collection is edited . If you wish to continue, unsaved changes will be lost</p>
            <a class="tiny button" href="<?php echo $this->url('user/logout'); ?>"><i class="fa fa-sign-out"></i>&nbsp; Logout</a>
            <a class="close-reveal-modal">&#215;</a>
        </div>
        <?php
            echo $this->inlineScript()->prependFile($this->basePath() . '/js/app.js')
                                      ->prependFile($this->basePath() . '/bower_components/foundation/js/foundation.min.js')
                                      ->prependFile($this->basePath() . '/bower_components/jquery/dist/jquery.min.js')
        ;?>
        <script type="text/javascript">
            $(document).ready(function (){
                $('.open-recent-modal').click(function(e) {
                    e.preventDefault();
                    var target = $(this).attr('href');
                    $('.recent-collection-name').text($.trim($(this).text()));
                    $('#confirm-open-recent').attr('href', target);
                    $('#recent-modal').foundation('reveal', 'open');
                });
            });
        </script>
    </body>
</html>
