<?php echo $this->doctype(); ?>
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Kivi '. $this->translate('Refgen'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/stylesheets/font-awesome.css')
                        ->prependStylesheet($this->basePath() . '/stylesheets/app.css')
                        ->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:400,700|Roboto+Slab:300')
        ; ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/bower_components/modernizr/modernizr.js');
        ?>
    </head>
    <body>
    <?php
    // Urls
    $homeUrl = $this->url('home');
    $standardRedirectUrl = '?redirect=' . urlencode($_SERVER['REQUEST_URI']);
    ?>
        <nav class="top-bar" data-topbar>
            <ul class="title-area">
                <li class="name">
                    <h1>
                        <a href="<?php echo $homeUrl; ?>">Refgen
                            <small id="beta">Beta</small>
                        </a>
                    </h1>
                </li>
                <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
            </ul>
            <section class="top-bar-section">
                <ul class="left">
                <?php if($this->hasAccess('Collection\Controller\Collection', 'new')): ?>
                    <?php //variables
                        $newCollectionUrl = $this->url('collection/new') . $standardRedirectUrl;
                        $openCollectionUrl = $this->url('collection/list') . $standardRedirectUrl;
                        $recents = $this->collections()->recents($this->activeCollection()->getOpenCollectionId());
                    ?>
                    <li class="divider"></li>
                    <li class="has-dropdown"><a href="#"><span class="fa fa-list"></span> Collections</a>
                        <ul class="dropdown">
                        <?php if($this->activeCollection()->isEdited()): ?>
                            <li>
                                <a href="<?php echo $newCollectionUrl; ?>" data-reveal-id="modal-new">
                                    <span class="fa fa-file"></span> New
                                </a>
                                <div id="modal-new" class="reveal-modal small" data-reveal>
                                    <h2>New collection</h2>
                                    <p class="lead">Your active collection is edited . If you wish to continue, unsaved changes will be lost</p>
                                    <a class="tiny button" href="<?php echo $newCollectionUrl; ?>"><span class="fa fa-file"></span> New Collection</a>
                                    <a class="close-reveal-modal">&#215;</a>
                                </div>
                            </li>
                        <?php else: ?>
                            <li>
                                <a href="<?php echo $newCollectionUrl; ?>">
                                    <span class="fa fa-file"></span> New
                                </a>
                            </li>
                        <?php endif; ?> <!-- New -->
                        <?php if(count($recents)): ?>
                            <li>
                                <a href="<?php echo $openCollectionUrl; ?>">
                                    <span class="fa fa-folder-open"></span> Open
                                </a>
                            </li> <!-- Open -->
                            <li><label>Recents</label></li>
                            <?php foreach($recents as $collection): ?>
                                <?php $url = $this->url('collection/open', array('id' => $collection['id'])); ?>
                            <li>
                                <a href="<?php echo $url; ?>">
                                    <span class="fa fa-list-alt"></span> <?php echo $collection['name']; ?>
                                </a>
                            </li>
                            <?php endforeach; ?> <!-- Recents -->
                        <?php endif; ?> <!-- Open and Recents -->
                        </ul> <!-- ul.dropdown for collection -->
                    </li> <!-- li.has-dropdown for Collection Menu -->
                <?php endif; ?>
                </ul>
                <ul class="right">
                    <?php if($this->authService()->hasIdentity()): ?>
                        <?php
                        /** @var \User\Entity\User $identity */
                        $identity = $this->authService()->getIdentity();
                        $logoutUrl = $this->url('user/logout');
                        ?>
                    <li class="has-dropdown">
                        <a href="#">
                            <img id="profile-picture" src="<?php echo $identity->getPictureLink(); ?>"/>
                            <span><?php echo $identity->getFirstName(); ?></span>
                        </a>
                        <ul class="dropdown">
                            <?php if($this->activeCollection()->isEdited()): ?>
                            <li>
                                <a href="<?php echo $logoutUrl; ?>" data-reveal-id="modal-logout">
                                    <span class="fa fa-sign-out"></span> Log out
                                </a>
                                <div id="modal-logout" class="reveal-modal small" data-reveal>
                                    <h2>Logout</h2>
                                    <p class="lead">Your active collection is edited . If you wish to continue, unsaved changes will be lost</p>
                                    <a class="tiny button" href="<?php echo $logoutUrl; ?>"><span class="fa fa-sign-out"></span> Logout</a>
                                    <a class="close-reveal-modal">&#215;</a>
                                </div>
                            </li>
                            <?php else: ?>
                            <li>
                                <a href="<?php echo $logoutUrl; ?>">
                                    <span class="fa fa-sign-out"></span> Log out
                                </a>
                            </li>
                            <?php endif; ?>
                        </ul> <!-- ul.dropdown of profile -->
                    </li>
                    <?php else: ?>
                        <?php $loginUrl = $this->url('user/login') . $standardRedirectUrl; ?>
                    <li>
                        <a href="<?php echo $loginUrl; ?>">
                            <span class="fa fa-sign-in"></span> Log in
                        </a>
                    </li>
                    <?php endif; ?>
                    <li class="divider"></li>
                    <li class="has-form">
                        <form method="get" action="<?php echo $this->url('search'); ?>">
                            <div class="row collapse">
                                <div class="small-10 columns">
                                    <?php $term = isset($this->term) ? $this->term : ''; ?>
                                    <input type="search" name="term" id="txt-search"
                                           placeholder="Search via pubmed" value="<?php echo $term; ?>"/>
                                </div>
                                <div class="small-2 columns">
                                    <button type="submit" class="tiny button"><i class="fa fa-search"></i></button>
                                </div>
                            </div>

                        </form>
                    </li>

                </ul>
            </section>
        </nav>
        <div id="content">
            <div class="row">
                <?php
                    $flash = $this->flashMessenger();
                    $flash->setMessageOpenFormat('<div data-alert%s><a href="#" class="close">&times;</a>')
                          ->setMessageSeparatorString('<br/>')
                          ->setMessageCloseString('</div>');
                    echo $flash->render('error',   array('alert-box', 'alert'));
                    echo $flash->render('info',    array('alert-box', 'info'));
                    echo $flash->render('default', array('alert-box'));
                    echo $flash->render('success', array('alert-box', 'success'));
                ?>
            </div>
            <div class="row">
                <?php echo $this->content; ?>
            </div>
        </div>
        <footer id="page-footer">
            <div class="row">
                <div class="small-8 columns">
                    <p>&copy; 2013 - <?php echo date('Y') ?> by Kivi Designers</p>
                </div>
                <div class="small-4 columns">
                    <p><span class="hidden-for-medium-down">Follow us on </span><a href="https://plus.google.com/111116372537356525801" rel="publisher" target="_blank"><i class="fa fa-2x fa-google-plus-square"></i></a> <a href="https://www.facebook.com/pages/Kivi-Refgen/266507806889448"><i class="fa fa-2x fa-facebook-square"></i></a></p>
                </div>
            </div>
        </footer>
        <?php
            echo $this->inlineScript()->prependFile($this->basePath() . '/js/app.js')
                                      ->prependFile($this->basePath() . '/bower_components/foundation/js/foundation.min.js')
                                      ->prependFile($this->basePath() . '/bower_components/jquery/dist/jquery.min.js');
        ?>
    <?php if(in_array(getenv('APP_ENV'), array('production', 'staging'))): ?>
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-52996057-1', 'auto');
            ga('send', 'pageview');

        </script>
    <?php endif; ?>
    </body>
</html>
