<?php echo $this->doctype(); ?>
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Kivi '. $this->translate('Refgen'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/stylesheets/font-awesome.css')
                        ->prependStylesheet($this->basePath() . '/stylesheets/app.css')
                        ->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:400,700|Roboto+Slab:300')
        ; ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/bower_components/modernizr/modernizr.js');
        ?>
    </head>
    <body>
    <?php
    // Urls
    $homeUrl = $this->url('home');
    $standardRedirectUrl = '?redirect=' . urlencode($_SERVER['REQUEST_URI']);
    ?>
        <nav class="top-bar" data-topbar>
            <ul class="title-area">
                <li class="name">
                    <h1>
                        <a href="<?php echo $homeUrl; ?>">Refgen
                            <small id="beta">Beta</small>
                        </a>
                    </h1>
                </li>
                <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
            </ul>
            <section class="top-bar-section">
                <?php if($this->hasAccess('Collection\Controller\Collection', 'new')): ?>
                <ul class="left">
                    <?php //variables
                        $newCollectionUrl = $this->url('collection/new') . $standardRedirectUrl;
                        $openCollectionUrl = $this->url('collection/list') . $standardRedirectUrl;
                        $recents = $this->collections()->recents();
                    ?>
                    <li class="divider"></li>
                    <li class="has-dropdown"><a href="#"><span class="fa fa-list"></span> Collections</a>
                        <ul class="dropdown">
                        <?php if($this->activeCollection()->isEdited()): ?>
                            <li>
                                <a href="<?php echo $newCollectionUrl; ?>" data-reveal-id="modal-new">
                                    <span class="fa fa-file"></span> New
                                </a>
                                <div id="modal-new" class="reveal-modal small" data-reveal>
                                    <h2>New collection</h2>
                                    <p class="lead">Your active collection is edited . If you wish to continue, unsaved changes will be lost</p>
                                    <a class="tiny button" href="<?php echo $this->url('collection/new'); ?>"><i class="fa fa-file"></i>&nbsp; New Collection</a>
                                    <a class="close-reveal-modal">&#215;</a>
                                </div>
                            </li>
                        <?php else: ?>
                            <li>
                                <a href="<?php echo $newCollectionUrl; ?>">
                                    <span class="fa fa-file"></span> New
                                </a>
                            </li>
                        <?php endif; ?> <!-- New -->
                        <?php if(count($recents)): ?>
                            <li>
                                <a href="<?php echo $openCollectionUrl; ?>">
                                    <span class="fa fa-folder-open"></span> Open
                                </a>
                            </li> <!-- Open -->
                            <li><label>Recents</label></li>
                            <?php foreach($recents as $collection): ?>
                                <?php $url = $this->url('collection/open', array('id' => $collection['id'])); ?>
                            <li>
                                <a href="<?php echo $url; ?>">
                                    <span class="fa fa-list-alt"></span> <?php echo $collection['name']; ?>
                                </a>
                            </li>
                            <?php endforeach; ?> <!-- Recents -->
                        <?php endif; ?> <!-- Open and Recents -->
                        </ul> <!-- ul.dropdown for collection -->
                    </li> <!-- li.has-dropdown for Collection Menu -->
                </ul>
                <?php endif; ?>
                </ul>
                <ul class="right">
                    <?php if($this->authService()->hasIdentity()): ?>
                    <li class="has-dropdown">
                        <a href="#">
                            <img style="width:35px; height:35px; border:2px solid #fff; margin-right:10px;" src="<?php echo $this->authService()->getIdentity()->getPictureLink(); ?>"/>
                            <span><?php echo $this->authService()->getIdentity()->getFirstName(); ?></span>
                        </a>
                        <ul class="dropdown">
                            <li>
                            <?php if($this->activeCollection()->isEdited()): ?>
                                <a href="<?php echo $this->url('user/logout'); ?>" data-reveal-id="logout-modal">
                            <?php else: ?>
                                <a href="<?php echo $this->url('user/logout'); ?>">
                            <?php endif; ?>
                                <i class="fa fa-sign-out"></i>&nbsp; Log out</a></li>
                        </ul>
                    </li>
                    <?php else: ?>
                    <li><a href="<?php echo $this->url('user/login') . '?redirect=' . urlencode($_SERVER['REQUEST_URI']); ?>"><i class="fa fa-sign-in"></i>&nbsp; Log in</a></li>
                    <?php endif; ?>
                    <li class="divider"></li>
                    <li class="has-form">
                        <form method="get" action="<?php echo $this->url('search'); ?>">
                            <div class="row collapse">
                                <div class="small-10 columns">
                                    <input type="search" name="term" id="txt-search" placeholder="Search via pubmed"/>
                                </div>
                                <div class="small-2 columns">
                                    <button type="submit" class="tiny button"><span class="fa fa-search"></span></button>
                                </div>
                            </div>

                        </form>
                    </li>

                </ul>
            </section>
        </nav>
        <div id="content">
            <div class="row">
                <?php
                    $flash = $this->flashMessenger();
                    $flash->setMessageOpenFormat('<div data-alert%s><a href="#" class="close">&times;</a>')
                          ->setMessageSeparatorString('<br/>')
                          ->setMessageCloseString('</div>');
                    echo $flash->render('error',   array('alert-box', 'alert'));
                    echo $flash->render('info',    array('alert-box', 'info'));
                    echo $flash->render('default', array('alert-box'));
                    echo $flash->render('success', array('alert-box', 'success'));
                ?>
            </div>
            <div class="row">
                <?php echo $this->content; ?>
            </div>
        </div>
        <footer id="page-footer">
            <div class="row">
                <div class="large-12 columns">
                    <p>&copy; 2013 - <?php echo date('Y') ?> by Kivi Designers. <?php echo $this->translate('All rights reserved.') ?></p>
                </div>
            </div>
        </footer>
        <div id="open-modal" class="reveal-modal small" data-reveal>
            <h2>Open collection</h2>
            <p class="lead">Your active collection is edited . If you wish to continue, unsaved changes will be lost</p>
            <a class="tiny button" href="<?php echo $this->url('collection/list'); ?>"><i class="fa fa-folder-open"></i>&nbsp; Open Collection</a>
            <a class="close-reveal-modal">&#215;</a>
        </div>
        <div id="recent-modal" class="reveal-modal small" data-reveal>
            <h2>Open collection</h2>
            <p class="lead">Your active collection is edited . If you wish to continue, all unsaved changes will be lost</p>
            <a id='confirm-open-recent' class="tiny button" href=""><i class="fa fa-list-alt"></i>&nbsp; Open <span class="recent-collection-name"></span></a>
            <a class="close-reveal-modal">&#215;</a>
        </div>
        <div id="logout-modal" class="reveal-modal small" data-reveal>
            <h2>Logout</h2>
            <p class="lead">Your active collection is edited . If you wish to continue, unsaved changes will be lost</p>
            <a class="tiny button" href="<?php echo $this->url('user/logout'); ?>"><i class="fa fa-sign-out"></i>&nbsp; Logout</a>
            <a class="close-reveal-modal">&#215;</a>
        </div>
        <?php
            echo $this->inlineScript()->prependFile($this->basePath() . '/js/app.js')
                                      ->prependFile($this->basePath() . '/bower_components/foundation/js/foundation.min.js')
                                      ->prependFile($this->basePath() . '/bower_components/jquery/dist/jquery.min.js')
        ;?>
        <script type="text/javascript">
            $(document).ready(function (){
                $('.open-recent-modal').click(function(e) {
                    e.preventDefault();
                    var target = $(this).attr('href');
                    $('.recent-collection-name').text($.trim($(this).text()));
                    $('#confirm-open-recent').attr('href', target);
                    $('#recent-modal').foundation('reveal', 'open');
                });
            });
        </script>
    </body>
</html>
