        <?php $this->headMeta()
                   ->appendName('keywords', 'vancouver citation, vancouver style, vancouver style citation, vancouver citation style, vancouver references style, vancouver style referencing, vancouver referencing style, referencing vancouver citation, citation search, vancouver, cite pubmed journal articles, cite medical articles, reference citing, reference citations, bibliography citations, citation bibliography, vancouver pubmed')
                   ->appendName('description', 'Create and organize references, citations and bibliography in Vancouver style from articles indexed in Pubmed across various devices with just a few clicks.'); ?>

            <div class="large-12 columns">
                <div class="row">
                    <div class="medium-8 medium-offset-2 columns end">
                        <h1 style="text-align: center;">One step less</h1>
                        <blockquote>Writing a research paper with correctly formatted citation is a challenge for many of us since it involves doing a technical work of bibliography where we have to take care of punctuations and stuff. Let Kivi Refgen make this formatting work ease for you, leaving you free to focus on your writing.</blockquote>
                        <p style="text-align: center;">Kivi Refgen is based on Vancouver style, a primary referencing system used by many scientific and biomedical journals. We help you to cite your references to produce an impressive and perfect bibliography in Vancouver style.</p>
                    </div>
                </div>

                <div class="row">
                    <div class="medium-4 columns">
                        <h2 style="text-align: center;"><i class="fa fa-search" style="color: #faa900;"></i>&nbsp; Search</h2>
                        <p style="text-align: center;">Search for articles related to your research topic from pubmed database and generate a perfect bibliography by citing your references in Vancouver style.</p>
                    </div>
                    <div class="medium-4 columns">
                        <h2 style="text-align: center;"><i class="fa fa-briefcase" style="color: #faa900;"></i>&nbsp; Organize</h2>
                        <p style="text-align: center;">Enables to create multiple citations of articles and also facilates to organize, store and manage them as personalized collections.</p>
                    </div>
                    <div class="medium-4 columns">
                        <h2 style="text-align: center;"><i class="fa fa-share" style="color: #faa900;"></i>&nbsp; Export</h2>
                        <p style="text-align: center;">Able to export references in proper citation formats to a word document in just a click.</p>
                    </div>
                </div>
                <div class="row">
                    <div class="medium-6 medium-offset-3 columns end">
                        <h3 style="text-align: center;">In the future</h3>
                        <p style="text-align: center;">We will extend the support for other databases in addition to Pubmed. Also we are working on including other reference styles apart from Vancouver.</p>
                    </div>
                </div>
            </div>

