            <div class="large-8 columns">
                <section id="articles">
                    <?php
                    $this->partialLoop()->setObjectKey('article');
                    echo $this->partialLoop('partials/article-truncated', $this->result);
                    ?>
                </section>
            </div>
            <div class="large-4 columns">
                <?php echo $this->activeCollection()->render(); ?>
            </div>


