<?php
    /** @var \Article\Entity\Article $article */
    $article = $this->result;
    $this->headTitle()->prepend($this->term);
?>
<div class="large-8 columns">
    <section id="articles">
        <?php echo $this->partial('partials/article.phtml', array('article' => $article)); ?>
    </section>
</div>
<div class="large-4 columns">
    <?php echo $this->activeCollection()->render(); ?>
</div>


