            <div class="large-8 columns">
                <section id="articles">
                    <?php
                        $this->partialLoop()->setObjectKey('article');
                        echo $this->partialLoop('partials/article-truncated', $this->paginator);
                    ?>
                    <div class="pagination-centered">
                    <?php
                        echo $this->paginationControl(
                            $this->paginator,
                            'Sliding',
                            'partials/pagination',
                            array(
                                'urlTemplate' => '/search/' . $this->term . '/page/%page%'
                            )
                        );
                    ?>
                    </div>
                </section>
            </div>
            <div class="large-4 columns">
                <?php echo $this->activeCollection()->render(); ?>
            </div>


